### ISSUE TITLE
Failed to get app info for `visionatrix` from the Appstore

### ISSUE THREAD

**Issue by SagarGi** [cloud-py-api/visionatrix#1]
### Question
I was trying to install `visionatrix` on nextcloud as `ExApp` but ran into problem with `Failed to get app info for `visionatrix` from the Appstore` while registering the app (deploying the app). 

AFAIK the app needs to be on Nextcloud app store to use it as nextcloud `ExApp`. Is `visionatrix` available on app store? or is there any way i can install it on nextcloud?  @bigcat88 @andrey18106

**Comment by bigcat88** [comment]
It will be available for Nextcloud 30, it is currently only in development, so it is not yet in the AppStore.

If you want to test the video card, you can put the original Visionatrix next to the Nextcloud for now.

**Comment by SagarGi** [comment]
@bigcat88 did you mean using `visionatrix` as standalone and not as a ExApp? or it is possible to install it as ex app in development setup?

**Comment by bigcat88** [comment]
I mean, if you want to know right now what this ExApp will be capable - just install Visionatrix from here: https://github.com/Visionatrix/Visionatrix


I can theoretically tell you how to install what is now in this repository as ExApp, but I would not like to waste time on this, because a lot of functionality is still missing, and I need to have time to check everything before there is a **freeze feature** in the Nextcloud Server repo.

**Comment by SagarGi** [comment]
@bigcat88 thanks for the information. But is there any way that i can install `Visionatrix` in nextcloud as `Exapp`. I would just want to see and check how it would look as `Exapp` in `Nextcloud` itself. I can see in the screenshots of `Visionatrix` in `Nextcloud` being installed as `ExApp`. Any documentation or information regarding the installation would be helpful. Or is it possible that i build the docker image for `visionatrix` (from Dockerfile) and manual install from `app_api` app?

**Comment by bigcat88** [comment]
If you have NC30 you can do something like this: `docker exec master-stable30-1 sudo -u www-data php occ app_api:app:register visionatrix --force-scopes --info-xml https://raw.githubusercontent.com/cloud-py-api/visionatrix/main/appinfo/info.xml`

The main part here is `php occ app_api:app:register visionatrix --force-scopes --info-xml https://raw.githubusercontent.com/cloud-py-api/visionatrix/main/appinfo/info.xml`

Deploy Daemon should be created with correspondent GPU type.
